name: unikl_skillswap
description: "Azwin's and Alyssa's UniKL SkillSwap fyp project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.3.4
  email_validator: ^3.0.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.1 
  table_calendar: ^3.0.9
  url_launcher: ^6.2.2
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/SkillSwap_Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/SkillSwap_Logo.png"